import Head from 'next/head'
import Header from '../components/Header'
import PostCard from '../components/PostCard'
import { MediumContext } from '../context/MediumContext'
import { useContext } from 'react'

export default function Home() {

  const { users, posts } = useContext(MediumContext)
  console.log(users, posts)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Header/>
        { posts.map(post => (
        <PostCard post={post} key={post.id}/>
        ))}
        {/* <h1>Hello world</h1> */}
      </main>
    </>
  )
}
